In [1]:
import os
import pandas as pd
input_csv_path = os.path.join("E4-GA.csv")
input_data_set = pd.read_csv(input_csv_path)
input_data_set.head()

,Time,Mean-X,Variance-X,Skewness-X,Kurtosis-X,RMS-X,Mean-Y,Variance-Y,Skewness-Y,Kurtosis-Y,RMS-Y,Mean-Z,Variance-Z,Skewness-Z,Kurtosis-Z,RMS-Z,Label
0,18:21:03.212,0.234375,0.000000,0.000000,0.000000,0.054932,0.015625,0.000000,0.000000,0.0,0.000244,0.953125,0.000000,0.000000,0.0,0.908447,0
1,18:21:03.213,0.234375,0.000000,0.000000,0.000000,0.054932,0.015625,0.000000,0.000000,0.0,0.000244,0.953125,0.000000,0.000000,0.0,0.908447,0
2,18:21:03.213,0.229167,0.000081,-1.732051,0.000000,0.052572,0.015625,0.000000,0.000000,0.0,0.000244,0.953125,0.000000,0.000000,0.0,0.908447,0
3,18:21:03.213,0.226562,0.000081,0.000000,-6.000000,0.051392,0.015625,0.000000,0.000000,0.0,0.000244,0.953125,0.000000,0.000000,0.0,0.908447,0
4,18:21:03.213,0.225000,0.000073,0.608581,-3.333333,0.050684,0.018750,0.000049,2.236068,5.0,0.000391,0.956250,0.000049,2.236068,5.0,0.914453,0

In [2]:
input_data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54858 entries, 0 to 54857
Data columns (total 17 columns):
Time          54858 non-null object
Mean-X        54858 non-null float64
Variance-X    54858 non-null float64
Skewness-X    54858 non-null float64
Kurtosis-X    54858 non-null float64
RMS-X         54858 non-null float64
Mean-Y        54858 non-null float64
Variance-Y    54858 non-null float64
Skewness-Y    54858 non-null float64
Kurtosis-Y    54858 non-null float64
RMS-Y         54858 non-null float64
Mean-Z        54858 non-null float64
Variance-Z    54858 non-null float64
Skewness-Z    54858 non-null float64
Kurtosis-Z    54858 non-null float64
RMS-Z         54858 non-null float64
Label         54858 non-null int64
dtypes: float64(15), int64(1), object(1)
memory usage: 7.1+ MB

In [3]:
input_data_set.describe()

,Mean-X,Variance-X,Skewness-X,Kurtosis-X,RMS-X,Mean-Y,Variance-Y,Skewness-Y,Kurtosis-Y,RMS-Y,Mean-Z,Variance-Z,Skewness-Z,Kurtosis-Z,RMS-Z,Label
count,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000,54858.000000
mean,0.359042,0.014059,0.109205,1.110299,0.329421,-0.018875,0.013330,0.044642,1.515313,0.476794,0.386829,0.008805,-0.004515,0.829913,0.213186,0.108808
std,0.432454,0.032662,1.277196,4.681413,0.291775,0.680918,0.029262,1.476373,5.872714,0.406011,0.234729,0.018458,1.267771,4.729404,0.187504,0.311401
min,-0.876250,0.000000,-5.000000,-6.000000,0.000000,-1.031250,0.000000,-5.000000,-2.800000,0.000000,-0.715000,0.000000,-5.000000,-2.173913,0.000215,0.000000
25%,0.075000,0.000061,-0.398655,-0.886886,0.079482,-0.666250,0.000034,-0.295124,-0.997553,0.011836,0.235625,0.000059,-0.427734,-1.137372,0.065337,0.000000
50%,0.311875,0.002131,0.028302,-0.170922,0.170908,-0.058750,0.000936,0.000000,-0.194993,0.609585,0.393125,0.001530,0.000000,-0.427260,0.171069,0.000000
75%,0.773125,0.012836,0.589223,0.865678,0.615896,0.833750,0.014968,0.517950,0.592885,0.851035,0.515625,0.011058,0.434783,0.549296,0.273721,0.000000
max,1.085625,0.704405,5.000000,25.000000,1.215596,1.285625,0.642303,5.000000,25.000000,1.832217,1.098750,0.296145,5.000000,25.000000,1.233379,1.000000

In [4]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(input_data_set, test_size = 0.2, random_state = 42)

print("Data set length: ", len(input_data_set))
print("Train set length: ", len(train_set), " Percentage of orig. data set length: ", (float(len(train_set)) / len(input_data_set)))
print("Test set length: ", len(test_set), " Percentage of orig. data set length: ", (float(len(test_set)) / len(input_data_set)))

('Data set length: ', 54858)
('Train set length: ', 43886, ' Percentage of orig. data set length: ', 0.7999927084472639)
('Test set length: ', 10972, ' Percentage of orig. data set length: ', 0.20000729155273617)

In [5]:
def get_value_label_matrices(data_set):
    labels = data_set["Label"].copy().values
    values = data_set[[
        "Mean-X",
        "Variance-X",
        "RMS-X",
        "Skewness-X",
        "Kurtosis-X",
        "Mean-Y",
        "Variance-Y",
        "RMS-Y",
        "Kurtosis-Y",
        "Skewness-Y",
        "Mean-Z",
        "Variance-Z",
        "RMS-Z",
        "Kurtosis-Z",
        "Skewness-Z"
    ]].copy().values
    
    # Sanity check ... the number of value / label records should match
    print("Parsed ", len(values), " values and ", len(labels), " labels")
    return values, labels

In [6]:
training_values, training_labels = get_value_label_matrices(train_set)

('Parsed ', 43886, ' values and ', 43886, ' labels')

In [7]:
test_values, test_labels = get_value_label_matrices(test_set)

('Parsed ', 10972, ' values and ', 10972, ' labels')

In [8]:
from sklearn.ensemble import RandomForestClassifier

rfClf = RandomForestClassifier(n_estimators=100)

rfClf = rfClf.fit(training_values, training_labels)

In [9]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

def generate_predictions_and_cross_validate(clf, values, labels):
    validator_num = 10 # number of validators to use ... feel free to play with this
    
    # generate the predicted labels with the provided classifer ...
    predicted_labels = cross_val_predict(clf, values, labels, cv = validator_num)
    
    # what predictions did the classifier generate?
    actual_predictions = confusion_matrix(labels, predicted_labels)
    print("Actual Predictions: ")
    print(actual_predictions)
    
    # what predictions *SHOULD* the classifier have generated?
    perfect_predictions = confusion_matrix(labels, labels)
    print("Perfect Predictions: ")
    print(perfect_predictions)
    
    # Let's see how we did ...
    score = cross_val_score(clf, values, labels, cv = validator_num, scoring = "accuracy")
    print("Classifier Accuracy: ", score)
    return predicted_labels

In [10]:
predicted_labels = generate_predictions_and_cross_validate(rfClf, training_values, training_labels)

Actual Predictions:
[[38980   133]
 [  189  4584]]
Perfect Predictions:
[[39113     0]
 [    0  4773]]
('Classifier Accuracy: ', array([0.99248292, 0.9929385 , 0.9952164 , 0.99179581, 0.99339107,
       0.9922516 , 0.99407475, 0.99361896, 0.99020055, 0.99111212]))

In [11]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(training_labels, predicted_labels)
print("Precision: ", precision)

recall = recall_score(training_labels, predicted_labels)
print("Recall: ", recall)

fscore = f1_score(training_labels, predicted_labels)
print("F Score: ", fscore)

('Precision: ', 0.9718041127835488)
('Recall: ', 0.9604022627278441)
('F Score: ', 0.9660695468914647)

In [13]:
# Once you have the precision, recall, and f-score where you want them,
# you can evaluate the test set as well!

predicted_test_labels = generate_predictions_and_cross_validate(rfClf, test_values, test_labels)

test_precision = precision_score(test_labels, predicted_test_labels)
print("Test Precision: ", test_precision)

test_recall = recall_score(test_labels, predicted_test_labels)
print("Test Recall: ", test_recall)

test_fscore = f1_score(test_labels, predicted_test_labels)
print("Test F-Score: ", test_fscore)

Actual Predictions:
[[9655  121]
 [ 244  952]]
Perfect Predictions:
[[9776    0]
 [   0 1196]]
('Classifier Accuracy: ', array([0.96721311, 0.97449909, 0.96903461, 0.97540984, 0.96721311,
       0.96539162, 0.96441606, 0.96532847, 0.96259124, 0.96806569]))
('Test Precision: ', 0.8872320596458527)
('Test Recall: ', 0.7959866220735786)
('Test F-Score: ', 0.8391361833406789)